### ISSUE TITLE
An instruction can be saved from get_rip

### ISSUE THREAD

**Issue by eliotmiranda** [GlinkieGamesInc/longjmp_win64#1]
This is a non-issue, but get_rip reads
```
get_rip PROC
	mov	rdx, rsp
	mov rax, [rdx]
	ret
get_rip ENDP
```
and can of course be written as
```
get_rip PROC
	mov rax, [rsp]
	ret
get_rip ENDP
```

**Comment by glinkiegames** [comment]
Nice catch, and thank you for bringing that to my attention. This will be corrected shortly 🙂

> This is a non-issue, but get_rip reads
> 
> ```
> get_rip PROC
> 	mov	rdx, rsp
> 	mov rax, [rdx]
> 	ret
> get_rip ENDP
> ```
> 
> and can of course be written as
> 
> ```
> get_rip PROC
> 	mov rax, [rsp]
> 	ret
> get_rip ENDP
> ```

**Comment by pglinker** [comment]
@eliotmiranda, it has been fixed. Thanks again! 😎👍
